name: amar_dokan_app
description: AmarDokan Is A POS And Shop Management App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  app_new_version_check: ^0.0.3
  countup: ^0.1.4
  http: ^1.0.0
  flutter_riverpod: ^2.4.1
  simple_animation_transition: ^0.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.4
  dio: ^5.3.3
  encrypt: ^5.0.3
  gif: ^2.2.0
  flutter_overlay_loader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21



flutter:

  uses-material-design: true

  assets:
    - pubspec.yaml
    - assets/logo/
    - assets/image/
    - assets/fonts/
    - i18n/


  fonts:
    - family: Ador
      fonts:
        - asset: assets/fonts/AdorVR.ttf


